courses/urls.py
from django.urls import path

from courses.views import (
    ManageCourseListView,
    CourseCreateView,
    CourseUpdateView,
    CourseDeleteView,
    CourseModuleUpdateView,
    ContentCreateUpdateView,
    ContentDeleteView,
    ModuleContentListView,
    ModuleOrderView,
    ContentOrderView,
    CourseListView,
    CourseDetailView,
)

app_name = 'courses'

urlpatterns = [
    # работа с курсами
    path('list/', ManageCourseListView.as_view(), name='manage_course_list'),  # список курсов пользователя
    path('create/', CourseCreateView.as_view(), name='course_create'),  # создание нового курса
    path('<int:pk>/update/', CourseUpdateView.as_view(), name='course_update'),  # изменение курса
    path('<int:pk>/delete/', CourseDeleteView.as_view(), name='course_delete'),  # удаление курса

    # список | добавление | изменение | удаление модулей
    path('<int:pk>/module/', CourseModuleUpdateView.as_view(), name='module_update'),

    # content create | update | delete
    path('module/<int:module_id>/content/<str:model_name>/create/', ContentCreateUpdateView.as_view(),
         name='content_create'),  # создать контент
    path('module/<int:module_id>/content/<str:model_name>/update/<int:pk>/', ContentCreateUpdateView.as_view(),
         name='content_update'),  # изменить контент
    path('content/<int:content_id>/delete/', ContentDeleteView.as_view(), name='content_delete'),  # удалить контент
    # список контента в модуле
    path('module/<int:module_id>/list/', ModuleContentListView.as_view(), name='module_content_list'),

    # change order (взаимодействуют с обработчиками js и изменяют order у Module и Content)
    path('module/order/', ModuleOrderView.as_view(), name='module_order_change'),
    path('content/order/', ContentOrderView.as_view(), name='content_order_change'),

    # просмотр курсов для учащихся
    path('subject/<slug:subject_slug>/', CourseListView.as_view(), name='course_list_subject'),  # список по предмету
    path('', CourseListView.as_view(), name='course_list'),  # список
    path('<slug:slug>/', CourseDetailView.as_view(), name='course_detail'),  # список
]

education/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls', namespace='courses')),
    path('students/', include('students.urls', namespace='students')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('api/', include('courses.api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # django-debug-toolbar
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

templates/_inc/header.html
<!--<a href="/" class="logo">-->
<a href="{% url 'courses:manage_course_list' %}" class="logo">
    <i class="fa fa-handshake-o" aria-hidden="true"></i>
<!--    <i class="fa fa-coffee" aria-hidden="true"></i>-->
    Educa
</a>
{% for i in 'aaaaa' %}
&nbsp;
{% endfor %}
<a href="{% url 'courses:manage_course_list' %}">
    Мои курсы&nbsp;
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
</a>
&nbsp;&nbsp;
<a href="{% url 'courses:course_list' %}">
    Все курсы&nbsp;<i class="fa fa-list-ol" aria-hidden="true"></i>
</a>
<ul class="menu">

    {% if request.user.is_authenticated %}
    <li>
        <a href="{% url 'logout' %}">
            Выйти&nbsp;
            <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
        </a>
    </li>
    {% else %}
    <li>
        <a href="{% url 'login' %}">
            Войти&nbsp;
            <i class="fa fa-sign-in fa-lg" aria-hidden="true"></i>
        </a>
    </li>
    {% endif %}
</ul>